# Initial pipeline test. Gain access to AMD Headnode.
image: python
pipelines:
  default:
    - step:
        script:
          - ssh bitbucket@portal.computefaster.com -p 13022 ./amd-test.sh
    - step:
        script:
	  - ssh bitbucket@portal.computefaster.com -p 11022 ./p8-test.sh
